package com.min.sample.data.local.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.min.sample.data.model.SearchBean;
import com.min.sample.data.model.FailReqRecord;

import com.min.sample.data.local.db.dao.SearchBeanDao;
import com.min.sample.data.local.db.dao.FailReqRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchBeanDaoConfig;
    private final DaoConfig failReqRecordDaoConfig;

    private final SearchBeanDao searchBeanDao;
    private final FailReqRecordDao failReqRecordDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchBeanDaoConfig = daoConfigMap.get(SearchBeanDao.class).clone();
        searchBeanDaoConfig.initIdentityScope(type);

        failReqRecordDaoConfig = daoConfigMap.get(FailReqRecordDao.class).clone();
        failReqRecordDaoConfig.initIdentityScope(type);

        searchBeanDao = new SearchBeanDao(searchBeanDaoConfig, this);
        failReqRecordDao = new FailReqRecordDao(failReqRecordDaoConfig, this);

        registerDao(SearchBean.class, searchBeanDao);
        registerDao(FailReqRecord.class, failReqRecordDao);
    }
    
    public void clear() {
        searchBeanDaoConfig.clearIdentityScope();
        failReqRecordDaoConfig.clearIdentityScope();
    }

    public SearchBeanDao getSearchBeanDao() {
        return searchBeanDao;
    }

    public FailReqRecordDao getFailReqRecordDao() {
        return failReqRecordDao;
    }

}
